# Dependabot Configuration for Saraiva Vision
# Automated dependency updates for security and maintenance
# See: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates

version: 2
updates:
  # Frontend dependencies (npm)
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "03:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 10
    reviewers:
      - "saraiva-vision-devops"
    assignees:
      - "saraiva-vision-devops"
    labels:
      - "dependencies"
      - "security"
      - "frontend"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    versioning-strategy: auto
    # Group dependencies to reduce PR noise
    groups:
      security-patches:
        patterns:
          - "*"
        update-types:
          - "patch"
      minor-updates:
        patterns:
          - "*"
        update-types:
          - "minor"

  # Backend API dependencies (npm)
  - package-ecosystem: "npm"
    directory: "/api"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 10
    reviewers:
      - "saraiva-vision-devops"
    assignees:
      - "saraiva-vision-devops"
    labels:
      - "dependencies"
      - "security"
      - "backend"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    versioning-strategy: auto
    groups:
      security-patches:
        patterns:
          - "*"
        update-types:
          - "patch"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "05:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 5
    reviewers:
      - "saraiva-vision-devops"
    labels:
      - "dependencies"
      - "ci-cd"
    commit-message:
      prefix: "ci"

  # Docker dependencies (if using Docker)
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "03:00"
      timezone: "America/Sao_Paulo"
    open-pull-requests-limit: 3
    reviewers:
      - "saraiva-vision-devops"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "chore(docker)"

# Security-specific configuration
# Allow Dependabot to access private registries (if needed)
registries:
  npm-registry:
    type: npm-registry
    url: https://registry.npmjs.org

# Ignore specific dependencies (with justification)
ignore:
  # Example: Ignore major version updates for stable dependencies
  # - dependency-name: "react"
  #   update-types: ["version-update:semver-major"]
  #   reason: "Major React updates require thorough testing"