[extend]
    useDefault = true

[[rules]]
id = "custom-generic-api-key"
description = "Generic API Key"
regex = '''(?i)(api[_-]?key|secret|token)\s*[:=]\s*['\"][A-Za-z0-9_\-]{16,}['\"]'''
tags = ["apikey"]
[[rules.allowlist.paths]]
description = "Allow lockfiles"
regex = '''(package-lock.json|pnpm-lock.yaml)'''

