rules:
  # JavaScript/TypeScript Security best practices
  - id: js.insecure-eval
    patterns:
      - pattern: eval(...)
    message: Avoid eval()
    severity: ERROR
    languages: [javascript, typescript]

  - id: ts.react-unsafe-dangerouslysetinnerhtml
    patterns:
      - pattern: |
          <... dangerouslySetInnerHTML={{...}} ... />
    message: Avoid dangerouslySetInnerHTML where possible or sanitize strictly.
    severity: WARNING
    languages: [typescript, javascript]

  # PHP/WordPress best practices (simplified examples)
  - id: php.unsanitized-input
    patterns:
      - pattern: $_GET[$X]
    message: Sanitize/validate input from $_GET
    severity: WARNING
    languages: [php]

  - id: wp.direct-db-access
    patterns:
      - pattern: new \WPDB(...)
    message: Prefer WPDB global or prepared queries with $wpdb->prepare.
    severity: INFO
    languages: [php]

