version: '3.8'

# Saraiva Vision Container Volume Configuration
# This file defines persistent volume configurations for both development and production environments

# Base Volume Definitions
volumes:
  # Frontend Volumes
  frontend_node_modules:
    driver: local
    name: saraiva-vision-frontend-node-modules
    labels:
      - "saraiva.vision.service=frontend"
      - "saraiva.vision.type=node_modules"

  frontend_build_cache:
    driver: local
    name: saraiva-vision-frontend-build-cache
    labels:
      - "saraiva.vision.service=frontend"
      - "saraiva.vision.type=build_cache"

  # API Volumes
  api_node_modules:
    driver: local
    name: saraiva-vision-api-node-modules
    labels:
      - "saraiva.vision.service=api"
      - "saraiva.vision.type=node_modules"

  api_logs:
    driver: local
    name: saraiva-vision-api-logs
    labels:
      - "saraiva.vision.service=api"
      - "saraiva.vision.type=logs"

  # WordPress Volumes
  wordpress_data:
    driver: local
    name: saraiva-vision-wordpress-data
    labels:
      - "saraiva.vision.service=wordpress"
      - "saraiva.vision.type=uploads"

  wordpress_themes:
    driver: local
    name: saraiva-vision-wordpress-themes
    labels:
      - "saraiva.vision.service=wordpress"
      - "saraiva.vision.type=themes"

  wordpress_plugins:
    driver: local
    name: saraiva-vision-wordpress-plugins
    labels:
      - "saraiva.vision.service=wordpress"
      - "saraiva.vision.type=plugins"

  wordpress_db:
    driver: local
    name: saraiva-vision-wordpress-db
    labels:
      - "saraiva.vision.service=wordpress"
      - "saraiva.vision.type=database"

  # Database Volumes
  mysql_data:
    driver: local
    name: saraiva-vision-mysql-data
    labels:
      - "saraiva.vision.service=database"
      - "saraiva.vision.type=data"

  mysql_config:
    driver: local
    name: saraiva-vision-mysql-config
    labels:
      - "saraiva.vision.service=database"
      - "saraiva.vision.type=config"

  mysql_backup:
    driver: local
    name: saraiva-vision-mysql-backup
    labels:
      - "saraiva.vision.service=database"
      - "saraiva.vision.type=backup"

  # Nginx Volumes
  nginx_logs:
    driver: local
    name: saraiva-vision-nginx-logs
    labels:
      - "saraiva.vision.service=nginx"
      - "saraiva.vision.type=logs"

  nginx_cache:
    driver: local
    name: saraiva-vision-nginx-cache
    labels:
      - "saraiva.vision.service=nginx"
      - "saraiva.vision.type=cache"

  nginx_ssl:
    driver: local
    name: saraiva-vision-nginx-ssl
    labels:
      - "saraiva.vision.service=nginx"
      - "saraiva.vision.type=ssl"

  # Redis Volumes
  redis_data:
    driver: local
    name: saraiva-vision-redis-data
    labels:
      - "saraiva.vision.service=redis"
      - "saraiva.vision.type=data"

  redis_config:
    driver: local
    name: saraiva-vision-redis-config
    labels:
      - "saraiva.vision.service=redis"
      - "saraiva.vision.type=config"

  # Monitoring Volumes
  grafana_data:
    driver: local
    name: saraiva-vision-grafana-data
    labels:
      - "saraiva.vision.service=monitoring"
      - "saraiva.vision.type=data"

  prometheus_data:
    driver: local
    name: saraiva-vision-prometheus-data
    labels:
      - "saraiva.vision.service=monitoring"
      - "saraiva.vision.type=data"

  # Development Volumes
  dev_frontend_source:
    driver: local
    name: saraiva-vision-dev-frontend-source
    labels:
      - "saraiva.vision.service=frontend"
      - "saraiva.vision.environment=development"
      - "saraiva.vision.type=source"

  dev_api_source:
    driver: local
    name: saraiva-vision-dev-api-source
    labels:
      - "saraiva.vision.service=api"
      - "saraiva.vision.environment=development"
      - "saraiva.vision.type=source"

  dev_wordpress_source:
    driver: local
    name: saraiva-vision-dev-wordpress-source
    labels:
      - "saraiva.vision.service=wordpress"
      - "saraiva.vision.environment=development"
      - "saraiva.vision.type=source"

# Development Volume Mounts
x-development-volumes:
  &development-volumes
  volumes:
    # Frontend development volumes
    - ./src:/app/src:cached
    - ./public:/app/public:cached
    - ./index.html:/app/index.html:cached
    - ./vite.config.js:/app/vite.config.js:cached
    - ./server-dev.js:/app/server-dev.js:cached
    - ./package.json:/app/package.json:cached
    - frontend_node_modules:/app/node_modules
    - frontend_build_cache:/app/.vite

    # API development volumes
    - ./server.js:/app/server.js:cached
    - ./api:/app/api:cached
    - ./package.json:/app/package.json:cached
    - api_node_modules:/app/node_modules
    - api_logs:/app/logs

    # WordPress development volumes
    - ./wordpress-local:/var/www/html:cached
    - wordpress_plugins:/var/www/html/wp-content/plugins/saraiva-vision:cached
    - wordpress_themes:/var/www/html/wp-content/themes:cached
    - wordpress_data:/var/www/html/wp-content/uploads

    # Nginx configuration volumes
    - ./nginx-health.conf:/etc/nginx/nginx.conf:cached
    - ./nginx-configs:/etc/nginx/conf.d:cached
    - nginx_logs:/var/log/nginx
    - nginx_cache:/var/cache/nginx

    # SSL certificates (development)
    - ./ssl:/etc/ssl:cached

# Production Volume Mounts
x-production-volumes:
  &production-volumes
  volumes:
    # Production volumes (read-only where possible)
    - frontend_build_cache:/app/.vite:ro
    - api_logs:/app/logs:rw
    - wordpress_themes:/var/www/html/wp-content/themes:ro
    - wordpress_plugins:/var/www/html/wp-content/plugins:ro
    - wordpress_data:/var/www/html/wp-content/uploads:rw
    - nginx_logs:/var/log/nginx:rw
    - nginx_cache:/var/cache/nginx:rw
    - /etc/letsencrypt:/etc/letsencrypt:ro

    # Database volumes
    - mysql_data:/var/lib/mysql:rw
    - mysql_config:/etc/mysql/conf.d:ro
    - mysql_backup:/backup:rw

    # Redis volumes
    - redis_data:/data:rw
    - redis_config:/etc/redis:ro

# Database-specific Volume Configuration
x-database-volumes:
  &database-volumes
  volumes:
    - mysql_data:/var/lib/mysql:rw
    - mysql_config:/etc/mysql/conf.d:rw
    - mysql_backup:/backup:rw
    - ./mysql-conf.d:/etc/mysql/conf.d:cached

# WordPress-specific Volume Configuration
x-wordpress-volumes:
  &wordpress-volumes
  volumes:
    - wordpress_data:/var/www/html/wp-content/uploads:rw
    - wordpress_themes:/var/www/html/wp-content/themes:rw
    - wordpress_plugins:/var/www/html/wp-content/plugins:rw
    - wordpress_db:/var/www/html/wp-content/databases:rw
    - ./wordpress-config:/var/www/html/wp-config.php:cached

# Service-specific Volume Templates
x-frontend-volumes:
  &frontend-volumes
  volumes:
    - frontend_node_modules:/app/node_modules
    - frontend_build_cache:/app/.vite
    - ./src:/app/src:cached
    - ./public:/app/public:cached

x-api-volumes:
  &api-volumes
  volumes:
    - api_node_modules:/app/node_modules
    - api_logs:/app/logs
    - ./server.js:/app/server.js:cached
    - ./api:/app/api:cached

x-nginx-volumes:
  &nginx-volumes
  volumes:
    - nginx_logs:/var/log/nginx
    - nginx_cache:/var/cache/nginx
    - /etc/letsencrypt:/etc/letsencrypt:ro

# Backup and Restore Volume Configuration
x-backup-volumes:
  &backup-volumes
  volumes:
    - mysql_backup:/backup/mysql:rw
    - wordpress_data:/backup/wordpress:ro
    - ./backups:/backups:rw
    - ./scripts/backup:/scripts/backup:ro

# Development-specific Volume Bind Mounts
x-development-bind-mounts:
  &development-bind-mounts
  volumes:
    # Source code bind mounts
    - .:/workspace:cached
    - /workspace/node_modules
    - /workspace/.vite

    # Configuration files
    - ./.env.development:/app/.env:cached
    - ./.env.local:/app/.env.local:cached

    # Development tools
    - /usr/local/bin/node:/usr/local/bin/node:ro
    - /usr/local/bin/npm:/usr/local/bin/npm:ro

# Production-specific Volume Constraints
x-production-volume-constraints:
  &production-volume-constraints
  volumes:
    # Read-only source code
    - ./dist:/app/dist:ro
    - ./public:/app/public:ro

    # Read-only configurations
    - ./nginx-health.conf:/etc/nginx/nginx.conf:ro
    - ./nginx-configs:/etc/nginx/conf.d:ro

    # Writable data volumes
    - nginx_logs:/var/log/nginx:rw
    - wordpress_data:/var/www/html/wp-content/uploads:rw
    - mysql_data:/var/lib/mysql:rw

# Volume Performance Optimization
x-volume-performance:
  &volume-performance
  driver_opts:
    type: none
    o: bind
    device: /mnt/saraiva-vision/${COMPOSE_PROJECT_NAME:-saraiva-vision}/${VOLUME_NAME:-data}

# Volume Security Configuration
x-volume-security:
  &volume-security
  driver_opts:
    type: tmpfs
    device: tmpfs
    o: "rw,size=1g,uid=1000,gid=1000"

# Persistent Data Volume Configuration
x-persistent-data:
  &persistent-data
  volumes:
    # User data persistence
    - wordpress_data:/var/www/html/wp-content/uploads
    - mysql_data:/var/lib/mysql
    - redis_data:/data

    # Configuration persistence
    - nginx_ssl:/etc/ssl
    - mysql_config:/etc/mysql/conf.d
    - redis_config:/etc/redis

    # Log persistence
    - nginx_logs:/var/log/nginx
    - api_logs:/app/logs

# Temporary Volume Configuration
x-temporary-volumes:
  &temporary-volumes
  volumes:
    # Temporary volumes that don't need persistence
    - tmp:/tmp
    - /tmp
    - /run

# Cache Volume Configuration
x-cache-volumes:
  &cache-volumes
  volumes:
    # Cache volumes that can be cleared
    - frontend_build_cache:/app/.vite
    - nginx_cache:/var/cache/nginx
    - redis_cache:/tmp/redis

# Development Workspace Volume
x-dev-workspace:
  &dev-workspace
  volumes:
    # Development workspace with all source files
    - .:/workspace:delegated
    - /workspace/node_modules
    - /workspace/.vite
    - /workspace/dist
    - /workspace/logs

    # IDE and tool configurations
    - ~/.vscode:/home/node/.vscode:cached
    - ~/.gitconfig:/home/node/.gitconfig:ro

    # Development certificates
    - ./ssl:/workspace/ssl:cached

# Production Deployment Volumes
x-production-deployment:
  &production-deployment
  volumes:
    # Production deployment volumes
    - /var/www/saraiva-vision/current:/app:ro
    - /var/log/saraiva-vision:/var/log
    - /etc/letsencrypt:/etc/letsencrypt:ro

    # Shared volumes
    - saraiva-vision-shared:/shared

    # SSL certificates
    - /etc/ssl/saraiva-vision:/etc/ssl:ro

# Backup Volume Configuration
x-backup-config:
  &backup-config
  volumes:
    # Backup directories
    - ./backups:/backups:rw
    - ./mysql-backup:/mysql-backup:rw
    - ./wordpress-backup:/wordpress-backup:rw

    # Backup scripts
    - ./scripts/backup:/scripts/backup:ro

    # Schedule configuration
    - ./crontab:/etc/crontabs/root:ro

# Volume Monitoring and Logging
x-volume-monitoring:
  &volume-monitoring
  volumes:
    # Volume monitoring logs
    - ./logs/volume-monitoring:/var/log/volume-monitoring:rw

    # Volume usage statistics
    - ./metrics/volume-usage:/var/metrics/volume-usage:rw

    # Volume cleanup logs
    - ./logs/volume-cleanup:/var/log/volume-cleanup:rw