version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      target: build
    ports:
      - "3002:3002"
      - "5173:5173"
    volumes:
      - ./src:/app/src:cached
      - ./public:/app/public:cached
      - ./index.html:/app/index.html:cached
      - ./vite.config.js:/app/vite.config.js:cached
      - ./package.json:/app/package.json:cached
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://api:3001
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0", "--port", "5173"]
    depends_on:
      api:
        condition: service_healthy
    networks:
      - internal

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "3001:3001"
      - "9229:9229"
    volumes:
      - ./server.js:/app/server.js:cached
      - ./api:/app/api:cached
      - ./.env.development:/app/.env:cached
      - /app/node_modules
    environment:
      - NODE_ENV=development
    command: ["node", "--inspect=0.0.0.0:9229", "server.js"]
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - internal

  wordpress:
    build:
      context: .
      dockerfile: Dockerfile.wordpress
    volumes:
      - ./wordpress-local:/var/www/html:cached
      - wordpress_data:/var/www/html/wp-content/uploads
    environment:
      - WORDPRESS_DEBUG=true
    healthcheck:
      test: ["CMD-SHELL", "php-fpm-healthcheck || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - internal

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:cached
      - ./nginx-configs:/etc/nginx/conf.d:cached
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      frontend:
        condition: service_healthy
      api:
        condition: service_healthy
      wordpress:
        condition: service_healthy
    networks:
      - internal

volumes:
  wordpress_data:

networks:
  internal:
    driver: bridge
