version: '3.8'

services:
  # Aplicação React (build)
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: saraivavisao-app
    restart: unless-stopped
    networks:
      - saraivavisao-network

  # Nginx como proxy reverso
  nginx:
    image: nginx:alpine
    container_name: saraivavisao-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./dist:/usr/share/nginx/html
      - ./ssl:/etc/nginx/ssl
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /etc/ssl/certs:/etc/ssl/certs:ro
      - /etc/ssl/private:/etc/ssl/private:ro
    networks:
      - saraivavisao-network

  # Certbot para SSL (opcional)
  certbot:
    image: certbot/certbot
    container_name: saraivavisao-certbot
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt
      - /var/www/certbot:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - saraivavisao-network

networks:
  saraivavisao-network:
    driver: bridge

volumes:
  ssl-certs:
  web-root: