version: '3.8'

# Saraiva Vision Environment Variables and Secrets Configuration
# This file defines environment variables and secret management for all services

# Environment Variable Templates
x-common-env:
  &common-env
  environment:
    # Application Environment
    - NODE_ENV=${NODE_ENV:-development}
    - APP_ENV=${APP_ENV:-development}
    - APP_DEBUG=${APP_DEBUG:-true}

    # Service Discovery
    - SERVICE_NAME=${SERVICE_NAME:-saraiva-vision}
    - SERVICE_VERSION=${SERVICE_VERSION:-2.0.0}
    - SERVICE_DISCOVERY=${SERVICE_DISCOVERY:-dns}

    # Timezone and Locale
    - TZ=${TZ:-America/Sao_Paulo}
    - LANG=${LANG:-pt_BR.UTF-8}
    - LC_ALL=${LC_ALL:-pt_BR.UTF-8}

    # Health Check Configuration
    - HEALTH_CHECK_ENABLED=${HEALTH_CHECK_ENABLED:-true}
    - HEALTH_CHECK_INTERVAL=${HEALTH_CHECK_INTERVAL:-30}
    - HEALTH_CHECK_TIMEOUT=${HEALTH_CHECK_TIMEOUT:-10}
    - HEALTH_CHECK_RETRIES=${HEALTH_CHECK_RETRIES:-3}

# Frontend Environment Variables
x-frontend-env:
  &frontend-env
  <<: *common-env
  environment:
    # Frontend Configuration
    - FRONTEND_PORT=${FRONTEND_PORT:-3002}
    - VITE_API_URL=${VITE_API_URL:-http://localhost:3001/api}
    - VITE_WORDPRESS_URL=${VITE_WORDPRESS_URL:-http://localhost:8083/wp-json}
    - VITE_GOOGLE_MAPS_API_KEY=${VITE_GOOGLE_MAPS_API_KEY:-}
    - VITE_SUPABASE_URL=${VITE_SUPABASE_URL:-}
    - VITE_SUPABASE_KEY=${VITE_SUPABASE_KEY:-}

    # Development Configuration
    - VITE_DEV_SERVER_HOST=${VITE_DEV_SERVER_HOST:-0.0.0.0}
    - VITE_DEV_SERVER_PORT=${VITE_DEV_SERVER_PORT:-5173}
    - VITE_DEV_SERVER_HTTPS=${VITE_DEV_SERVER_HTTPS:-false}

    # Build Configuration
    - VITE_BUILD_TARGET=${VITE_BUILD_TARGET:-es2015}
    - VITE_BUILD_MINIFY=${VITE_BUILD_MINIFY:-true}
    - VITE_BUILD_SOURCEMAP=${VITE_BUILD_SOURCEMAP:-false}

    # Analytics and Monitoring
    - VITE_GTM_ENABLED=${VITE_GTM_ENABLED:-false}
    - VITE_GTM_ID=${VITE_GTM_ID:-}
    - VITE_ANALYTICS_ENABLED=${VITE_ANALYTICS_ENABLED:-true}

    # Feature Flags
    - VITE_ENABLE_SERVICE_WORKER=${VITE_ENABLE_SERVICE_WORKER:-true}
    - VITE_ENABLE_PWA=${VITE_ENABLE_PWA:-true}
    - VITE_ENABLE_OFFLINE=${VITE_ENABLE_OFFLINE:-false}

# API Environment Variables
x-api-env:
  &api-env
  <<: *common-env
  environment:
    # API Configuration
    - API_PORT=${API_PORT:-3001}
    - API_VERSION=${API_VERSION:-v1}
    - API_PREFIX=${API_PREFIX:-/api}

    # Rate Limiting
    - RATE_LIMIT_ENABLED=${RATE_LIMIT_ENABLED:-true}
    - RATE_LIMIT_WINDOW_MS=${RATE_LIMIT_WINDOW_MS:-60000}
    - RATE_LIMIT_MAX_REQUESTS=${RATE_LIMIT_MAX_REQUESTS:-100}

    # External Service URLs
    - WORDPRESS_URL=${WORDPRESS_URL:-http://wordpress:8083}
    - GOOGLE_MAPS_API_URL=${GOOGLE_MAPS_API_URL:-https://maps.googleapis.com}
    - SUPABASE_URL=${SUPABASE_URL:-}
    - SUPABASE_KEY=${SUPABASE_KEY:-}

    # API Keys
    - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
    - GOOGLE_PLACES_API_KEY=${GOOGLE_PLACES_API_KEY}

    # Security Configuration
    - CORS_ENABLED=${CORS_ENABLED:-true}
    - CORS_ORIGIN=${CORS_ORIGIN:-*}
    - CORS_METHODS=${CORS_METHODS:-GET,POST,PUT,DELETE,OPTIONS}
    - CORS_HEADERS=${CORS_HEADERS:-Content-Type,Authorization}

    # Session and Authentication
    - SESSION_SECRET=${SESSION_SECRET}
    - JWT_SECRET=${JWT_SECRET}
    - COOKIE_SECRET=${COOKIE_SECRET}

    # Email Configuration
    - EMAIL_SERVICE=${EMAIL_SERVICE:-resend}
    - EMAIL_API_KEY=${EMAIL_API_KEY}
    - EMAIL_FROM=${EMAIL_FROM:-noreply@saraivavision.com.br}

    # Logging Configuration
    - LOG_LEVEL=${LOG_LEVEL:-info}
    - LOG_FORMAT=${LOG_FORMAT:-json}
    - LOG_FILE=${LOG_FILE:-/app/logs/api.log}

# WordPress Environment Variables
x-wordpress-env:
  &wordpress-env
  environment:
    # WordPress Configuration
    - WORDPRESS_DEBUG=${WORDPRESS_DEBUG:-false}
    - WORDPRESS_DB_HOST=${WORDPRESS_DB_HOST:-db:3306}
    - WORDPRESS_DB_USER=${WORDPRESS_DB_USER:-wordpress}
    - WORDPRESS_DB_PASSWORD=${WORDPRESS_DB_PASSWORD}
    - WORDPRESS_DB_NAME=${WORDPRESS_DB_NAME:-wordpress}
    - WORDPRESS_TABLE_PREFIX=${WORDPRESS_TABLE_PREFIX:-wp_}
    - WORDPRESS_CONFIG_EXTRA=${WORDPRESS_CONFIG_EXTRA:-}

    # WordPress URLs
    - WP_HOME=${WP_HOME:-https://saraivavision.com.br}
    - WP_SITEURL=${WP_SITEURL:-https://saraivavision.com.br}

    # WordPress Authentication Keys
    - AUTH_KEY=${AUTH_KEY}
    - SECURE_AUTH_KEY=${SECURE_AUTH_KEY}
    - LOGGED_IN_KEY=${LOGGED_IN_KEY}
    - NONCE_KEY=${NONCE_KEY}
    - AUTH_SALT=${AUTH_SALT}
    - SECURE_AUTH_SALT=${SECURE_AUTH_SALT}
    - LOGGED_IN_SALT=${LOGGED_IN_SALT}
    - NONCE_SALT=${NONCE_SALT}

    # WordPress Memory Limit
    - WORDPRESS_MEMORY_LIMIT=${WORDPRESS_MEMORY_LIMIT:-256M}

    # WordPress Upload Settings
    - WORDPRESS_UPLOAD_MAX_FILESIZE=${WORDPRESS_UPLOAD_MAX_FILESIZE:-64M}
    - WORDPRESS_POST_MAX_SIZE=${WORDPRESS_POST_MAX_SIZE:-64M}

    # WordPress Security
    - FORCE_SSL_ADMIN=${FORCE_SSL_ADMIN:-true}
    - DISALLOW_FILE_EDIT=${DISALLOW_FILE_EDIT:-true}
    - DISALLOW_FILE_MODS=${DISALLOW_FILE_MODS:-true}
    - AUTOMATIC_UPDATER_DISABLED=${AUTOMATIC_UPDATER_DISABLED:-true}
    - WP_AUTO_UPDATE_CORE=${WP_AUTO_UPDATE_CORE:-false}

# Database Environment Variables
x-database-env:
  &database-env
  environment:
    # MySQL Configuration
    - MYSQL_DATABASE=${MYSQL_DATABASE:-wordpress}
    - MYSQL_USER=${MYSQL_USER:-wordpress}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    - MYSQL_HOST=${MYSQL_HOST:-db}
    - MYSQL_PORT=${MYSQL_PORT:-3306}

    # MySQL Performance
    - MYSQL_INNODB_BUFFER_POOL_SIZE=${MYSQL_INNODB_BUFFER_POOL_SIZE:-256M}
    - MYSQL_INNODB_LOG_FILE_SIZE=${MYSQL_INNODB_LOG_FILE_SIZE:-64M}
    - MYSQL_MAX_CONNECTIONS=${MYSQL_MAX_CONNECTIONS:-151}

    # MySQL Security
    - MYSQL_ROOT_HOST=${MYSQL_ROOT_HOST:-%}
    - MYSQL_INITDB_SKIP_TZINFO=${MYSQL_INITDB_SKIP_TZINFO:-1}

    # MySQL Character Set
    - MYSQL_CHARACTER_SET_SERVER=${MYSQL_CHARACTER_SET_SERVER:-utf8mb4}
    - MYSQL_COLLATION_SERVER=${MYSQL_COLLATION_SERVER:-utf8mb4_unicode_ci}

# Redis Environment Variables
x-redis-env:
  &redis-env
  environment:
    - REDIS_PASSWORD=${REDIS_PASSWORD}
    - REDIS_PORT=${REDIS_PORT:-6379}
    - REDIS_HOST=${REDIS_HOST:-redis}
    - REDIS_DB=${REDIS_DB:-0}
    - REDIS_MAXMEMORY=${REDIS_MAXMEMORY:-256mb}
    - REDIS_MAXMEMORY_POLICY=${REDIS_MAXMEMORY_POLICY:-allkeys-lru}

# Nginx Environment Variables
x-nginx-env:
  &nginx-env
  environment:
    # Nginx Configuration
    - NGINX_HOST=${NGINX_HOST:-saraivavision.com.br}
    - NGINX_PORT=${NGINX_PORT:-80}
    - NGINX_SSL_PORT=${NGINX_SSL_PORT:-443}

    # Service Hosts
    - FRONTEND_HOST=${FRONTEND_HOST:-frontend:3000}
    - API_HOST=${API_HOST:-api:3001}
    - WORDPRESS_HOST=${WORDPRESS_HOST:-wordpress:8083}
    - DB_HOST=${DB_HOST:-db:3306}

    # SSL Configuration
    - SSL_CERTIFICATE=${SSL_CERTIFICATE:-/etc/letsencrypt/live/saraivavision.com.br/fullchain.pem}
    - SSL_CERTIFICATE_KEY=${SSL_CERTIFICATE_KEY:-/etc/letsencrypt/live/saraivavision.com.br/privkey.pem}

    # Performance Configuration
    - NGINX_WORKER_PROCESSES=${NGINX_WORKER_PROCESSES:-auto}
    - NGINX_WORKER_CONNECTIONS=${NGINX_WORKER_CONNECTIONS:-1024}
    - NGINX_KEEPALIVE_TIMEOUT=${NGINX_KEEPALIVE_TIMEOUT:-65}

    # Security Headers
    - NGINX_SSL_PROTOCOLS=${NGINX_SSL_PROTOCOLS:-TLSv1.2 TLSv1.3}
    - NGINX_SSL_CIPHERS=${NGINX_SSL_CIPHERS:-ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384}

# Monitoring Environment Variables
x-monitoring-env:
  &monitoring-env
  environment:
    - GRAFANA_PASSWORD=${GRAFANA_PASSWORD:-admin}
    - GRAFANA_USER=${GRAFANA_USER:-admin}
    - PROMETHEUS_RETENTION=${PROMETHEUS_RETENTION:-15d}
    - PROMETHEUS_SCRAPE_INTERVAL=${PROMETHEUS_SCRAPE_INTERVAL:-15s}

# Development-specific Environment Variables
x-development-env:
  &development-env
  environment:
    - NODE_ENV=development
    - APP_ENV=development
    - DEBUG=true
    - WORDPRESS_DEBUG=true
    - VITE_DEV_MODE=true

    # Development Services
    - DEV_MODE=true
    - DEV_RELOAD=true
    - DEV_SOURCE_MAPS=true

    # Development Hosts
    - DEV_HOST=localhost
    - DEV_DOMAIN=localhost
    - DEV_API_HOST=api.localhost
    - DEV_WORDPRESS_HOST=wordpress.localhost

    # Development Ports
    - DEV_FRONTEND_PORT=3002
    - DEV_API_PORT=3001
    - DEV_WORDPRESS_PORT=8083
    - DEV_NGINX_PORT=80

# Production-specific Environment Variables
x-production-env:
  &production-env
  environment:
    - NODE_ENV=production
    - APP_ENV=production
    - DEBUG=false
    - WORDPRESS_DEBUG=false

    # Production Configuration
    - PRODUCTION=true
    - LOG_LEVEL=warn
    - DISABLE_SOURCE_MAPS=true

    # Production URLs
    - PRODUCTION_DOMAIN=saraivavision.com.br
    - PRODUCTION_API_URL=https://saraivavision.com.br/api
    - PRODUCTION_WORDPRESS_URL=https://saraivavision.com.br/wp-json

    # Production Security
    - FORCE_SSL=true
    - HSTS_ENABLED=true
    - CSP_ENABLED=true

# Secret Management
x-secrets:
  &secrets
  secrets:
    # API Keys and Secrets
    google_maps_api_key:
      file: ./secrets/google_maps_api_key.txt
    google_places_api_key:
      file: ./secrets/google_places_api_key.txt
    supabase_url:
      file: ./secrets/supabase_url.txt
    supabase_key:
      file: ./secrets/supabase_key.txt

    # Authentication Secrets
    session_secret:
      file: ./secrets/session_secret.txt
    jwt_secret:
      file: ./secrets/jwt_secret.txt
    cookie_secret:
      file: ./secrets/cookie_secret.txt

    # Email Configuration
    email_api_key:
      file: ./secrets/email_api_key.txt

    # Database Secrets
    wordpress_db_password:
      file: ./secrets/wordpress_db_password.txt
    mysql_root_password:
      file: ./secrets/mysql_root_password.txt

    # WordPress Keys
    auth_key:
      file: ./secrets/wordpress_auth_key.txt
    secure_auth_key:
      file: ./secrets/wordpress_secure_auth_key.txt
    logged_in_key:
      file: ./secrets/wordpress_logged_in_key.txt
    nonce_key:
      file: ./secrets/wordpress_nonce_key.txt
    auth_salt:
      file: ./secrets/wordpress_auth_salt.txt
    secure_auth_salt:
      file: ./secrets/wordpress_secure_auth_salt.txt
    logged_in_salt:
      file: ./secrets/wordpress_logged_in_salt.txt
    nonce_salt:
      file: ./secrets/wordpress_nonce_salt.txt

    # Redis Secrets
    redis_password:
      file: ./secrets/redis_password.txt

    # SSL Configuration
    ssl_certificate:
      file: ./secrets/ssl_certificate.txt
    ssl_certificate_key:
      file: ./secrets/ssl_certificate_key.txt

    # Monitoring Secrets
    grafana_password:
      file: ./secrets/grafana_password.txt

# Environment-specific Configuration
services:
  # Development Services
  frontend:
    <<: [*frontend-env, *development-env]

  api:
    <<: [*api-env, *development-env]
    <<: *secrets

  wordpress:
    <<: *wordpress-env
    <<: *secrets

  nginx:
    <<: *nginx-env
    <<: *development-env

  # Production Services
  frontend-prod:
    profiles:
      - production
    <<: [*frontend-env, *production-env]

  api-prod:
    profiles:
      - production
    <<: [*api-env, *production-env]
    <<: *secrets

  wordpress-prod:
    profiles:
      - production
    <<: *wordpress-env
    <<: *production-env
    <<: *secrets

  nginx-prod:
    profiles:
      - production
    <<: [*nginx-env, *production-env]

# Environment File Management
x-env-files:
  &env-files
  env_file:
    - ./.env
    - ./.env.${NODE_ENV:-development}
    - ./.env.local
    - ./.env.${NODE_ENV:-development}.local

# Production Environment Files
x-prod-env-files:
  &prod-env-files
  env_file:
    - ./.env.production
    - ./.env.production.local
    - /etc/saraiva-vision/environment

# Development Environment Files
x-dev-env-files:
  &dev-env-files
  env_file:
    - ./.env.development
    - ./.env.development.local
    - ./.env.local