version: '3.8'

services:
  # WordPress CMS para Clínica Saraiva Vision
  wordpress:
    image: wordpress:6.6-php8.3-apache
    container_name: saraiva-wordpress
    restart: unless-stopped
    ports:
      - "8083:80"
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: saraiva_user
      WORDPRESS_DB_PASSWORD: saraiva_secure_2024
      WORDPRESS_DB_NAME: saraiva_vision_db
      WORDPRESS_TABLE_PREFIX: sv_
      
      # WordPress Configuration
      WORDPRESS_CONFIG_EXTRA: |
        // Configurações específicas da Clínica Saraiva Vision
        define('WP_DEBUG', true);
        define('WP_DEBUG_LOG', true);
        define('WP_DEBUG_DISPLAY', false);
        
        // Configurações para headless CMS
        define('DISALLOW_FILE_EDIT', true);
        define('FORCE_SSL_ADMIN', false);
        
        // CORS e API REST
        define('ALLOW_UNFILTERED_UPLOADS', true);
        
        // Clínica Saraiva Vision - Dr. Philipe Saraiva Cruz
        define('CLINIC_NAME', 'Clínica Saraiva Vision');
        define('DOCTOR_NAME', 'Dr. Philipe Saraiva Cruz');
        define('DOCTOR_CRM', 'CRM-MG 69.870');
        define('CLINIC_LOCATION', 'Caratinga, Minas Gerais');
    volumes:
      - wordpress_data:/var/www/html
      - ./wordpress-api-fix.php:/var/www/html/wp-content/mu-plugins/saraiva-api-fix.php
      - ./wp-config-fixed.php:/usr/local/etc/php/conf.d/wordpress-config.ini
    depends_on:
      - db
    networks:
      - saraiva_network

  # Database MySQL para WordPress
  db:
    image: mysql:8.0
    container_name: saraiva-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: saraiva_vision_db
      MYSQL_USER: saraiva_user
      MYSQL_PASSWORD: saraiva_secure_2024
      MYSQL_ROOT_PASSWORD: saraiva_root_2024
    volumes:
      - db_data:/var/lib/mysql
      - ./scripts/mysql-init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - saraiva_network

  # phpMyAdmin para administração (opcional)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: saraiva-phpmyadmin
    restart: unless-stopped
    ports:
      - "8084:80"
    environment:
      PMA_HOST: db
      PMA_USER: saraiva_user
      PMA_PASSWORD: saraiva_secure_2024
    depends_on:
      - db
    networks:
      - saraiva_network

volumes:
  wordpress_data:
    driver: local
  db_data:
    driver: local

networks:
  saraiva_network:
    driver: bridge

# Configuração específica para Clínica Saraiva Vision
# Dr. Philipe Saraiva Cruz - CRM-MG 69.870
# Caratinga, Minas Gerais