version: "3.9"

services:
  nginx:
    environment:
      APP_ENV: development
      NGINX_AUTO_RELOAD: "true"
    volumes:
      - ./infra/nginx/nginx.conf:/etc/nginx/nginx.conf:delegated
      - ./infra/nginx/conf.d:/etc/nginx/conf.d:delegated
      - ./infra/nginx/snippets:/etc/nginx/snippets:delegated
      - ./infra/nginx/templates:/etc/nginx/templates:delegated
      - ./infra/nginx/certs:/etc/nginx/certs:ro
      - wordpress_data:/var/www/html:ro
      - ./logs/nginx:/var/log/nginx
    extra_hosts:
      - "host.docker.internal:host-gateway"

  frontend:
    build:
      target: build
    command: ["node", "server-dev.js"]
    environment:
      NODE_ENV: development
      FRONTEND_PORT: 3002
      VITE_API_URL: http://localhost:3001
      VITE_WORDPRESS_URL: http://localhost:8080/wp-json
    ports:
      - "3002:3002"
      - "5173:5173"
    volumes:
      - ./src:/app/src:delegated
      - ./public:/app/public:delegated
      - ./index.html:/app/index.html:delegated
      - ./server-dev.js:/app/server-dev.js:delegated
      - ./vite.config.js:/app/vite.config.js:delegated
      - ./package.json:/app/package.json:delegated
      - ./package-lock.json:/app/package-lock.json:delegated
      - /app/node_modules
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://127.0.0.1:3002/health || exit 1"]

  api:
    build:
      target: build
    command: ["node", "--watch", "--inspect=0.0.0.0:9229", "server.js"]
    environment:
      NODE_ENV: development
      PORT: 3001
      WORDPRESS_URL: http://localhost:8080/wp-json
    ports:
      - "3001:3001"
      - "9229:9229"
    volumes:
      - ./server.js:/app/server.js:delegated
      - ./api:/app/api:delegated
      - ./package.json:/app/package.json:delegated
      - ./package-lock.json:/app/package-lock.json:delegated
      - /app/node_modules
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://127.0.0.1:3001/api/health || exit 1"]

  cms:
    environment:
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'http://localhost:8080');
        define('WP_SITEURL', 'http://localhost:8080');
        define('DISALLOW_FILE_EDIT', true);
        define('FORCE_SSL_ADMIN', false);
        define('WP_MEMORY_LIMIT', '256M');
        define('WP_DEBUG', true);
        define('WP_DEBUG_LOG', true);
        define('WP_DEBUG_DISPLAY', false);
        define('AUTOSAVE_INTERVAL', 60);
        define('WP_POST_REVISIONS', 15);
    ports:
      - "9000:9000"
    volumes:
      - ./wordpress-local/wp-content:/var/www/html/wp-content:delegated
      - wordpress_data:/var/www/html

  db:
    ports:
      - "3306:3306"
