version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      target: production
    restart: always
    ports:
      - "3002:3002"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
        reservations:
          cpus: '0.25'
          memory: 64M
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3002/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - internal
      - external

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    restart: always
    ports:
      - "3001:3001"
    env_file:
      - .env.production
    environment:
      - NODE_ENV=production
      - PORT=3001
      - HOST=0.0.0.0
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - internal
      - external

# WordPress temporarily disabled for quick deployment
  # wordpress:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.wordpress
  #   restart: always
  #   volumes:
  #     - wordpress_data:/var/www/html/wp-content/uploads
  #     - wordpress_db:/var/www/html/wp-content/databases
  #   environment:
  #     - WORDPRESS_DEBUG=false
  #   networks:
  #     - internal

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./nginx-configs/simple-production.conf:/etc/nginx/conf.d/default.conf:ro
      - nginx_logs:/var/log/nginx
      - /var/www/certbot:/var/www/certbot:ro
    environment:
      - NGINX_HOST=saraivavision.com.br
      - FRONTEND_HOST=frontend:3002
      - API_HOST=api:3001
      - WORDPRESS_HOST=wordpress:9000
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 128M
        reservations:
          cpus: '0.25'
          memory: 64M
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:80/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    depends_on:
      frontend:
        condition: service_started
      api:
        condition: service_healthy
    networks:
      - internal
      - external

volumes:
  wordpress_data:
  wordpress_db:
  nginx_logs:

networks:
  internal:
    driver: bridge
    internal: true
  external:
    driver: bridge
