# Main Docker Compose for Saraiva Vision Medical Clinic Website
# Supports dev, staging, and production profiles

services:
  # Frontend Service (Vite/React)
  frontend:
    build:
      context: .
      dockerfile: infra/docker/frontend/Dockerfile
      target: production
    container_name: saraiva-frontend
    restart: unless-stopped
    profiles:
      - dev
      - staging
      - prod
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    networks:
      - saraiva_network
    depends_on:
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Backend/API Service (Node.js)
  backend:
    build:
      context: .
      dockerfile: infra/docker/backend/Dockerfile
    container_name: saraiva-backend
    restart: unless-stopped
    profiles:
      - dev
      - staging
      - prod
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=3001
      - API_BASE_URL=${API_BASE_URL:-http://localhost:3001}
    env_file:
      - .env.production
    volumes:
      # Mount logs directory for persistence
      - ./logs:/app/logs
    networks:
      - saraiva_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx Proxy Service
  nginx:
    build:
      context: .
      dockerfile: infra/docker/nginx/Dockerfile
    container_name: saraiva-nginx
    restart: unless-stopped
    profiles:
      - staging
      - prod
    ports:
      - "${HTTP_PORT:-80}:80"
      - "${HTTPS_PORT:-443}:443"
    volumes:
      # SSL certificates (for production)
      - ./ssl:/etc/nginx/ssl:ro
      # Logs
      - ./logs/nginx:/var/log/nginx
    networks:
      - saraiva_network
    depends_on:
      - frontend
      - backend
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Development Frontend (with HMR)
  frontend-dev:
    build:
      context: .
      dockerfile: infra/docker/frontend/Dockerfile
      target: builder
    container_name: saraiva-frontend-dev
    profiles:
      - dev
    ports:
      - "5173:5173"
    environment:
      - NODE_ENV=development
      - VITE_API_BASE_URL=http://localhost:3001
    volumes:
      # Mount source code for hot reload
      - .:/app
      - /app/node_modules
    networks:
      - saraiva_network
    command: npm run dev -- --host 0.0.0.0

  # WordPress CMS (optional - using existing config)
  wordpress:
    extends:
      file: docker-compose.wordpress.yml
      service: wordpress
    profiles:
      - dev
      - staging
    networks:
      - saraiva_network

  # Database for WordPress
  db:
    extends:
      file: docker-compose.wordpress.yml
      service: db
    profiles:
      - dev
      - staging
    networks:
      - saraiva_network

# Networks
networks:
  saraiva_network:
    driver: bridge
    name: saraiva_network

# Volumes
volumes:
  # Persistent storage for logs
  logs:
    driver: local
  
  # SSL certificates
  ssl:
    driver: local
    
  # WordPress data (from existing config)
  wordpress_data:
    external: true
    
  # Database data (from existing config)  
  db_data:
    external: true