services:
  # Database for WordPress - starts first
  db:
    image: mysql:8.0
    container_name: saraiva-mysql
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: saraiva_vision_db
      MYSQL_USER: saraiva_user
      MYSQL_PASSWORD: saraiva_secure_2024
      MYSQL_ROOT_PASSWORD: saraiva_root_2024
    volumes:
      - db_data:/var/lib/mysql
      - ./scripts/mysql-init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - saraiva_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "saraiva_user", "--password=saraiva_secure_2024"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # WordPress CMS - depends on healthy database
  wordpress:
    image: wordpress:6.6-php8.3-apache
    container_name: saraiva-wordpress
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: saraiva_user
      WORDPRESS_DB_PASSWORD: saraiva_secure_2024
      WORDPRESS_DB_NAME: saraiva_vision_db
      WORDPRESS_TABLE_PREFIX: sv_
      WORDPRESS_CONFIG_EXTRA: |
        // Configurações específicas da Clínica Saraiva Vision
        define('WP_DEBUG', false);
        define('WP_DEBUG_LOG', true);
        define('WP_DEBUG_DISPLAY', false);
        define('DISALLOW_FILE_EDIT', true);
        define('FORCE_SSL_ADMIN', false);
        define('ALLOW_UNFILTERED_UPLOADS', true);
        // Clínica Saraiva Vision - Dr. Philipe Saraiva Cruz
        define('CLINIC_NAME', 'Clínica Saraiva Vision');
        define('DOCTOR_NAME', 'Dr. Philipe Saraiva Cruz');
        define('DOCTOR_CRM', 'CRM-MG 69.870');
        define('CLINIC_LOCATION', 'Caratinga, Minas Gerais');
    volumes:
      - wordpress_data:/var/www/html
      - ./wordpress-api-fix.php:/var/www/html/wp-content/mu-plugins/saraiva-api-fix.php:ro
    depends_on:
      db:
        condition: service_healthy
    networks:
      - saraiva_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/wp-json/wp/v2/"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  # API Server - Node.js backend
  api:
    build:
      context: .
      dockerfile: infra/docker/api/Dockerfile
    container_name: saraiva-api
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 3001
    networks:
      - saraiva_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Frontend - React application served by Nginx
  frontend:
    build:
      context: .
      dockerfile: infra/docker/frontend/Dockerfile
    container_name: saraiva-frontend
    restart: unless-stopped
    networks:
      - saraiva_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health.json"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Nginx Reverse Proxy - main entry point
  nginx:
    build:
      context: .
      dockerfile: infra/docker/nginx/Dockerfile
    container_name: saraiva-nginx
    restart: unless-stopped
    ports:
      - "8082:80"
    depends_on:
      frontend:
        condition: service_healthy
      api:
        condition: service_healthy
      wordpress:
        condition: service_healthy
    networks:
      - saraiva_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 15s

  # phpMyAdmin for database administration (optional)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: saraiva-phpmyadmin
    restart: unless-stopped
    ports:
      - "8084:80"
    environment:
      PMA_HOST: db
      PMA_USER: saraiva_user
      PMA_PASSWORD: saraiva_secure_2024
    depends_on:
      db:
        condition: service_healthy
    networks:
      - saraiva_network
    profiles:
      - admin

volumes:
  db_data:
    driver: local
  wordpress_data:
    driver: local

networks:
  saraiva_network:
    driver: bridge
    name: saraiva_network

# Health check endpoints:
# - Nginx: http://localhost:8082/health
# - Frontend: http://localhost:8082/health.json (proxied)
# - API: http://localhost:8082/api/health (proxied)
# - WordPress: http://localhost:8082/wp-json/wp/v2/ (proxied)
# - Database admin: http://localhost:8084 (phpmyadmin)