version: "3.9"

x-logging-defaults: &logging-defaults
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "5"

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    image: saraivavision/nginx:latest
    restart: unless-stopped
    environment:
      APP_ENV: production
      NGINX_AUTO_RELOAD: "false"
      FRONTEND_SERVICE_HOST: frontend
      FRONTEND_SERVICE_PORT: 80
      API_SERVICE_HOST: api
      API_SERVICE_PORT: 3001
      WORDPRESS_SERVICE_HOST: cms
      WORDPRESS_SERVICE_PORT: 9000
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://localhost/healthz || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    depends_on:
      frontend:
        condition: service_healthy
      api:
        condition: service_healthy
      cms:
        condition: service_healthy
    volumes:
      - wordpress_data:/var/www/html:ro
      - ./logs/nginx:/var/log/nginx
      - ./infra/nginx/certs:/etc/nginx/certs:ro
    networks:
      - edge
      - backend
    logging: *logging-defaults

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
      target: production
    image: saraivavision/frontend:latest
    restart: unless-stopped
    expose:
      - "80"
    environment:
      NODE_ENV: production
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://127.0.0.1/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    networks:
      - backend
    logging: *logging-defaults

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
      target: production
    image: saraivavision/api:latest
    restart: unless-stopped
    expose:
      - "3001"
    environment:
      NODE_ENV: production
      PORT: 3001
      WORDPRESS_URL: http://nginx/cms
    healthcheck:
      test: ["CMD-SHELL", "curl -sf http://127.0.0.1:3001/api/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 40s
    depends_on:
      cms:
        condition: service_healthy
    networks:
      - backend
    logging: *logging-defaults

  cms:
    build:
      context: .
      dockerfile: Dockerfile.wordpress
    image: saraivavision/wordpress:latest
    restart: unless-stopped
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: saraiva_wp
      WORDPRESS_DB_PASSWORD: change_me
      WORDPRESS_DB_NAME: saraivavision
      WORDPRESS_TABLE_PREFIX: sv_
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'https://saraivavision.local');
        define('WP_SITEURL', 'https://saraivavision.local/cms');
        define('DISALLOW_FILE_EDIT', true);
        define('FORCE_SSL_ADMIN', true);
        define('WP_MEMORY_LIMIT', '256M');
        define('AUTOSAVE_INTERVAL', 120);
        define('WP_POST_REVISIONS', 10);
        define('WP_DEBUG', false);
        define('WP_DISABLE_FATAL_ERROR_HANDLER', false);
    volumes:
      - wordpress_data:/var/www/html
      - ./infra/php/conf.d/uploads.ini:/usr/local/etc/php/conf.d/uploads.ini:ro
      - ./infra/php/conf.d/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini:ro
      - ./infra/php/php-fpm.d/www.conf:/usr/local/etc/php-fpm.d/zz-www.conf:ro
      - ./infra/php/healthcheck.sh:/usr/local/bin/php-fpm-healthcheck:ro
    healthcheck:
      test: ["CMD-SHELL", "/usr/local/bin/php-fpm-healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    depends_on:
      db:
        condition: service_healthy
    networks:
      - backend
    logging: *logging-defaults

  db:
    image: mysql:8.0
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password --max-connections=200 --innodb-buffer-pool-size=256M
    environment:
      MYSQL_DATABASE: saraivavision
      MYSQL_USER: saraiva_wp
      MYSQL_PASSWORD: change_me
      MYSQL_ROOT_PASSWORD: change_me_root
      TZ: America/Sao_Paulo
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 6
      start_period: 60s
    networks:
      - backend
    logging: *logging-defaults

networks:
  edge:
    driver: bridge
  backend:
    driver: bridge

volumes:
  mysql_data:
  wordpress_data:
