/**
 * Blog Posts Loader (Browser-Safe)
 * Imports pre-built posts.json generated at build-time
 * No Buffer/Node.js dependencies - pure browser-compatible code
 *
 * IMPORTANT: posts.json is generated by scripts/build-blog-posts.js
 * Run `npm run build:blog` before building the app
 */

import postsData from './posts.json';

// Import category configuration
export { categoryConfig } from './categoryConfig.js';

/**
 * Export pre-built posts array
 * All markdown parsing happened at build-time in Node.js environment
 */
export const blogPosts = postsData;

/**
 * Export categories list
 */
export const categories = [
  'Todas',
  'Prevenção',
  'Tratamento',
  'Tecnologia',
  'Dúvidas Frequentes'
];

/**
 * Export default for convenience
 */
export default blogPosts;

// Export individual post by slug helper
export const getPostBySlug = (slug) => {
  return blogPosts.find(post => post.slug === slug);
};

// Export posts by category helper
export const getPostsByCategory = (category) => {
  return blogPosts.filter(post => post.category === category);
};

// Export featured posts helper
export const getFeaturedPosts = () => {
  return blogPosts.filter(post => post.featured);
};

// Export recent posts helper
export const getRecentPosts = (limit = 3) => {
  return [...blogPosts]
    .sort((a, b) => new Date(b.date) - new Date(a.date))
    .slice(0, limit);
};
