openapi: 3.0.3
info:
  title: Podcast API
  description: API for managing podcast content synchronized with Spotify
  version: 1.0.0
  contact:
    name: Saraiva Vision API Support
    email: tech@saraivavision.com.br

servers:
  - url: https://saraivavision.com.br/api
    description: Production server
  - url: http://localhost:3000/api
    description: Development server

paths:
  /podcast/shows:
    get:
      summary: List podcast shows
      description: Get all active podcast shows
      operationId: listShows
      tags:
        - Podcast
      parameters:
        - name: active
          in: query
          schema:
            type: boolean
            default: true
          description: Filter by active status
      responses:
        '200':
          description: List of podcast shows
          content:
            application/json:
              schema:
                type: object
                properties:
                  shows:
                    type: array
                    items:
                      $ref: '#/components/schemas/PodcastShow'
                  total:
                    type: integer

  /podcast/shows/{id}/episodes:
    get:
      summary: List episodes for a show
      description: Get episodes for a specific podcast show
      operationId: listEpisodes
      tags:
        - Podcast
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Podcast show ID
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 50
            default: 20
          description: Number of episodes to return
        - name: offset
          in: query
          schema:
            type: integer
            minimum: 0
            default: 0
          description: Number of episodes to skip
        - name: featured
          in: query
          schema:
            type: boolean
          description: Filter by featured status
      responses:
        '200':
          description: List of podcast episodes
          content:
            application/json:
              schema:
                type: object
                properties:
                  episodes:
                    type: array
                    items:
                      $ref: '#/components/schemas/PodcastEpisode'
                  total:
                    type: integer
                  show:
                    $ref: '#/components/schemas/PodcastShow'

  /podcast/episodes/{id}:
    get:
      summary: Get episode details
      description: Get detailed information about a specific episode
      operationId: getEpisode
      tags:
        - Podcast
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
          description: Episode ID
      responses:
        '200':
          description: Episode details
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PodcastEpisodeDetails'
        '404':
          description: Episode not found

  /podcast/featured:
    get:
      summary: Get featured episodes
      description: Get episodes marked as featured for homepage display
      operationId: getFeaturedEpisodes
      tags:
        - Podcast
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            minimum: 1
            maximum: 10
            default: 3
      responses:
        '200':
          description: Featured episodes
          content:
            application/json:
              schema:
                type: object
                properties:
                  episodes:
                    type: array
                    items:
                      $ref: '#/components/schemas/PodcastEpisode'

  /podcast/sync:
    post:
      summary: Trigger manual sync
      description: Manually trigger synchronization with Spotify (admin only)
      operationId: triggerSync
      tags:
        - Podcast
      security:
        - BearerAuth: []
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                show_id:
                  type: string
                  format: uuid
                  description: Specific show to sync (optional)
                force:
                  type: boolean
                  default: false
                  description: Force sync even if recently synced
      responses:
        '200':
          description: Sync completed successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
                  synced_episodes:
                    type: integer
                  sync_duration_ms:
                    type: integer
        '401':
          description: Unauthorized
        '403':
          description: Insufficient permissions

  /podcast/admin/episodes/{id}:
    patch:
      summary: Update episode metadata
      description: Update episode metadata (admin only)
      operationId: updateEpisode
      tags:
        - Podcast
      security:
        - BearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/EpisodeUpdate'
      responses:
        '200':
          description: Episode updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PodcastEpisodeDetails'
        '401':
          description: Unauthorized
        '403':
          description: Insufficient permissions

components:
  schemas:
    PodcastShow:
      type: object
      properties:
        id:
          type: string
          format: uuid
        spotify_id:
          type: string
          example: "4rOoJ6Egrf8K2IrywzwOMk"
        name:
          type: string
          example: "Saúde Visual em Foco"
        description:
          type: string
          example: "Podcast sobre oftalmologia e cuidados com a visão"
        publisher:
          type: string
          example: "Clínica Saraiva Vision"
        language:
          type: string
          example: "pt-BR"
        explicit:
          type: boolean
          example: false
        total_episodes:
          type: integer
          example: 15
        image_url:
          type: string
          format: uri
          example: "https://i.scdn.co/image/ab6765630000ba8a..."
        spotify_url:
          type: string
          format: uri
          example: "https://open.spotify.com/show/4rOoJ6Egrf8K2IrywzwOMk"
        is_active:
          type: boolean
          example: true
        last_sync_at:
          type: string
          format: date-time
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    PodcastEpisode:
      type: object
      properties:
        id:
          type: string
          format: uuid
        spotify_id:
          type: string
          example: "4VqPOruhp5EdPBeR92t6lQ"
        title:
          type: string
          example: "Cuidados com a Visão no Diabetes"
        description:
          type: string
          example: "Episódio sobre os cuidados especiais que diabéticos devem ter com a visão."
        duration_ms:
          type: integer
          example: 1800000
        episode_number:
          type: integer
          example: 5
        season_number:
          type: integer
          example: 1
        release_date:
          type: string
          format: date
          example: "2025-01-15"
        explicit:
          type: boolean
          example: false
        image_url:
          type: string
          format: uri
        spotify_url:
          type: string
          format: uri
        is_featured:
          type: boolean
          example: false
        status:
          type: string
          enum: ["draft", "published", "archived", "hidden"]
          example: "published"

    PodcastEpisodeDetails:
      allOf:
        - $ref: '#/components/schemas/PodcastEpisode'
        - type: object
          properties:
            html_description:
              type: string
              example: "<p>Episódio sobre os cuidados especiais...</p>"
            languages:
              type: array
              items:
                type: string
              example: ["pt-BR"]
            audio_preview_url:
              type: string
              format: uri
              nullable: true
            show:
              $ref: '#/components/schemas/PodcastShow'
            synced_at:
              type: string
              format: date-time
            created_at:
              type: string
              format: date-time
            updated_at:
              type: string
              format: date-time

    EpisodeUpdate:
      type: object
      properties:
        is_featured:
          type: boolean
        status:
          type: string
          enum: ["draft", "published", "archived", "hidden"]
        episode_number:
          type: integer
          minimum: 1
        season_number:
          type: integer
          minimum: 1

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token from Supabase authentication

tags:
  - name: Podcast
    description: Podcast content management and synchronization