name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ci-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    name: Lint, Test, Build
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: Install dependencies
        run: |
          if [ -f package-lock.json ]; then
            npm ci --include=dev
          else
            npm install --include=dev
          fi

      - name: Lint (ESLint)
        run: npx eslint src

      - name: Unit tests (Vitest)
        run: npm run test:coverage

      - name: Build (Vite)
        run: npm run build

      - name: Smoke test (serve dist locally)
        env:
          DIST_DIR: dist
        run: |
          npx --yes http-server dist -p 4173 -s >/dev/null 2>&1 &
          SERVER_PID=$!
          # Aguarda servidor subir
          for i in {1..20}; do curl -sSf http://127.0.0.1:4173 >/dev/null && break || sleep 0.5; done
          # Verifica index atende
          curl -sSfI http://127.0.0.1:4173 | head -n 1
          # Executa verificação GTM apenas no pacote (sem SITE_URL)
          if [ -f scripts/verify-gtm.js ]; then
            node scripts/verify-gtm.js || echo 'GTM bundle verify failed (non-blocking)'
          else
            echo 'No scripts/verify-gtm.js found; skipping bundle verify.'
          fi
          kill $SERVER_PID || true

      - name: Verify HTML (html-validate)
        run: npm run verify:html

      - name: Verify GTM integration (bundle + site)
        env:
          SITE_URL: ${{ vars.SITE_URL || 'https://saraivavision.com.br' }}
          DIST_DIR: dist
          VITE_GTM_ID: ${{ secrets.VITE_GTM_ID || 'GTM-KF2NP85D' }}
        run: |
          if [ -f scripts/verify-gtm.js ]; then
            node scripts/verify-gtm.js || echo 'GTM verify failed (non-blocking in CI)'
          else
            echo 'No scripts/verify-gtm.js found; skipping.'
          fi

      - name: Upload production build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
          if-no-files-found: error
          retention-days: 7

  deploy:
    needs: build-test
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: dist
          path: dist
      - uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: "dist/*"
          target: ${{ secrets.SSH_TARGET || '/var/www/html' }}
      - uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            sudo systemctl reload nginx
