# .github/workflows/deploy-staging.yml

name: Deploy Nginx to Staging

on:
  push:
    branches:
      - staging
    paths:
      - 'saraivavision-staging.conf'
      - 'includes/**'
      - 'conf.d/**'
      - 'scripts/deploy-nginx.sh'

jobs:
  call-reusable-deploy:
    uses: ./.github/workflows/reusable-deploy-nginx.yml
    with:
      environment: staging
    secrets: inherit